import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'telemetry_error.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'telemetry_error.g.dart';

@freezed
class TelemetryError with _$TelemetryError {
  const factory TelemetryError({
    required int id,
    required String errorData,
    required int timestamp,
  }) = _TelemetryError;

  factory TelemetryError.fromJson(Map<String, dynamic> json) =>
      _$TelemetryErrorFromJson(json);
}
