import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'telemetry.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'telemetry.g.dart';

@freezed
class Telemetry with _$Telemetry {
  const factory Telemetry({
    required int telemetryId,
    required int altitude,
    required int timestamp,
    required int temperature,
    required int velocity,
    required int radiation,
  }) = _Telemetry;

  factory Telemetry.fromJson(Map<String, dynamic> json) =>
      _$TelemetryFromJson(json);
}
