import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'user.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
// part 'user.g.dart';

@freezed
class User with _$User {
  const factory User({
    required String username,
    required String email,
    required String id,
  }) = _User;
}
