// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBomZsGGJ9fIsWR8pMeYKCPpRZBCsKj08U',
    appId: '1:130261670803:web:75cbf2f8d93d31b19ee666',
    messagingSenderId: '130261670803',
    projectId: 'boardvote-822da',
    authDomain: 'boardvote-822da.firebaseapp.com',
    storageBucket: 'boardvote-822da.appspot.com',
    measurementId: 'G-7M94YZF958',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcT7n2FQlVoxkCS5iTwrL4GMDWDgMMweE',
    appId: '1:130261670803:android:5b39b6175e131d1b9ee666',
    messagingSenderId: '130261670803',
    projectId: 'boardvote-822da',
    storageBucket: 'boardvote-822da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDi6M2HOzWyeA1BGyNhoQzjVxS0p8ZmloI',
    appId: '1:130261670803:ios:1796a55b58ec08e59ee666',
    messagingSenderId: '130261670803',
    projectId: 'boardvote-822da',
    storageBucket: 'boardvote-822da.appspot.com',
    iosClientId: '130261670803-plpncgoi9g7msc7kaa1u6on9po69admf.apps.googleusercontent.com',
    iosBundleId: 'com.example.boardvote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDi6M2HOzWyeA1BGyNhoQzjVxS0p8ZmloI',
    appId: '1:130261670803:ios:1796a55b58ec08e59ee666',
    messagingSenderId: '130261670803',
    projectId: 'boardvote-822da',
    storageBucket: 'boardvote-822da.appspot.com',
    iosClientId: '130261670803-plpncgoi9g7msc7kaa1u6on9po69admf.apps.googleusercontent.com',
    iosBundleId: 'com.example.boardvote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBomZsGGJ9fIsWR8pMeYKCPpRZBCsKj08U',
    appId: '1:130261670803:web:4d43b116a36110909ee666',
    messagingSenderId: '130261670803',
    projectId: 'boardvote-822da',
    authDomain: 'boardvote-822da.firebaseapp.com',
    storageBucket: 'boardvote-822da.appspot.com',
    measurementId: 'G-CD15F0GVST',
  );

}